version = 3

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

  [[blocks.segments]]
  foreground = "#77E4F7"
  style = "plain"
  template = "{{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  foreground = "#FFE700"
  style = "plain"
  type = "git"
  template = "{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{end}}</> "
  
	[blocks.segments.properties]
    fetch_status = true
	commit_icon = "@"

  [[blocks.segments]]
  foreground_templates = [
	"{{if gt .Code 0}}red{{end}}",
	"{{if eq .Code 0}}#43D426{{end}}",
  ]
  style = "plain"
  template = "❯ "
  type = "text"

[[blocks]]
type = "rprompt"

  [[blocks.segments]]
  foreground = "#b497d6"
  style = "plain"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
  type = "elixir"

    [blocks.segments.properties]
    cache_duration = "24h"

  [[blocks.segments]]
  foreground = "#7FD5EA"
  style = "plain"
  template = "\ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
  type = "go"

    [blocks.segments.properties]
    cache_duration = "24h"

  [[blocks.segments]]
  foreground = "#42E66C"
  style = "plain"
  template = "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
  type = "node"

    [blocks.segments.properties]
    cache_duration = "24h"

  [[blocks.segments]]
  foreground = "#E64747"
  style = "plain"
  template = "\ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
  type = "ruby"

    [blocks.segments.properties]
    cache_duration = "24h"

  [[blocks.segments]]
  foreground = "#E4F34A"
  style = "plain"
  template = "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
  type = "python"

    [blocks.segments.properties]
    cache_duration = "24h"

  [[blocks.segments]]
  foreground = "#00C5C7"
  style = "plain"
  template = "   {{ .FormattedMs }} "
  type = "executiontime"

    [blocks.segments.properties]
    threshold = 2000
	style = "austin"

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}#43D426{{end}}",
]
style = "plain"
template = "❯ "
type = "text"
